"""
Товары магазина. Пока захардкожены — на этапе 5 переедут в БД.
Данные перенесены из frontend/app.js (PRODUCTS).
"""

PRODUCTS: dict[str, list[dict]] = {
    "ru": [
        {
            "id": 1,
            "emoji": "🧻",
            "category": "books",
            "name": "Свитки для уединения",
            "desc": "Пока сидишь — читаешь. Мудрые изречения и забавные истории. Два в одном!",
            "price": 333,
            "oldPrice": None,
        },
        {
            "id": 2,
            "emoji": "🧥",
            "category": "clothing",
            "name": 'Мантия "Переживший Чуму"',
            "desc": "Ограниченный тираж 1348 года. Согреет после любого апокалипсиса. 100% шерсть.",
            "price": 600,
            "oldPrice": None,
        },
        {
            "id": 3,
            "emoji": "🔒",
            "category": "clothing",
            "name": "Пояс верности",
            "desc": "Первое в мире средство контрацепции. Надёжно, как каменная стена.",
            "price": 1500,
            "oldPrice": None,
        },
        {
            "id": 4,
            "emoji": "📜",
            "category": "books",
            "name": "Индульгенция на неделю",
            "desc": "Все грехи прощены до следующего вторника. Действует только на этой неделе.",
            "price": 500,
            "oldPrice": None,
        },
        {
            "id": 5,
            "emoji": "🐴",
            "category": None,
            "name": "Запасная лошадь",
            "desc": "Никогда не знаешь, когда понадобится.",
            "price": 1800,
            "oldPrice": 2500,
        },
    ],
    "en": [
        {
            "id": 1,
            "emoji": "🧻",
            "category": "books",
            "name": "Scrolls for Solitude",
            "desc": "Read while you sit. Wise sayings and funny stories. Two in one!",
            "price": 333,
            "oldPrice": None,
        },
        {
            "id": 2,
            "emoji": "🧥",
            "category": "clothing",
            "name": 'Cloak "Plague Survivor"',
            "desc": "Limited edition from 1348. Warms after any apocalypse. 100% wool.",
            "price": 600,
            "oldPrice": None,
        },
        {
            "id": 3,
            "emoji": "🔒",
            "category": "clothing",
            "name": "Chastity Belt",
            "desc": "The world's first contraceptive. As reliable as a stone wall.",
            "price": 1500,
            "oldPrice": None,
        },
        {
            "id": 4,
            "emoji": "📜",
            "category": "books",
            "name": "Indulgence for a Week",
            "desc": "All sins forgiven until next Tuesday. Valid only this week.",
            "price": 500,
            "oldPrice": None,
        },
        {
            "id": 5,
            "emoji": "🐴",
            "category": None,
            "name": "Spare Horse",
            "desc": "You never know when you'll need it.",
            "price": 1800,
            "oldPrice": 2500,
        },
    ],
    "la": [
        {
            "id": 1,
            "emoji": "🧻",
            "category": "books",
            "name": "VOLUMINA SOLITUDINI",
            "desc": "Dum sedes, legis. Sententiae sapientes et fabulae iocosae. Duo in uno!",
            "price": 333,
            "oldPrice": None,
        },
        {
            "id": 2,
            "emoji": "🧥",
            "category": "clothing",
            "name": 'PALLIUM "PESTEM SUPERVIVI"',
            "desc": "Editio limitata anni 1348. Post quemlibet apocalypsin calefacit. 100% lana.",
            "price": 600,
            "oldPrice": None,
        },
        {
            "id": 3,
            "emoji": "🔒",
            "category": "clothing",
            "name": "CINGULUM CASTITATIS",
            "desc": "Primum in mundo contraceptivum. Firmum ut murus lapideus.",
            "price": 1500,
            "oldPrice": None,
        },
        {
            "id": 4,
            "emoji": "📜",
            "category": "books",
            "name": "INDULGENTIA HEBDOMADALIS",
            "desc": "Omnia peccata dimissa usque ad proximam diem Martis. Valet tantum hac hebdomade.",
            "price": 500,
            "oldPrice": None,
        },
        {
            "id": 5,
            "emoji": "🐴",
            "category": None,
            "name": "EQUUS SUBSIDIARIUS",
            "desc": "Numquam scis quando opus erit.",
            "price": 1800,
            "oldPrice": 2500,
        },
    ],
}